// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/evm.proto

package evm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Evm service

func NewEvmEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Evm service

type EvmService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Evm_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Evm_PingPongService, error)
}

type evmService struct {
	c    client.Client
	name string
}

func NewEvmService(name string, c client.Client) EvmService {
	return &evmService{
		c:    c,
		name: name,
	}
}

func (c *evmService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Evm.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evmService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Evm_StreamService, error) {
	req := c.c.NewRequest(c.name, "Evm.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &evmServiceStream{stream}, nil
}

type Evm_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type evmServiceStream struct {
	stream client.Stream
}

func (x *evmServiceStream) Close() error {
	return x.stream.Close()
}

func (x *evmServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *evmServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *evmServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *evmServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *evmService) PingPong(ctx context.Context, opts ...client.CallOption) (Evm_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Evm.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &evmServicePingPong{stream}, nil
}

type Evm_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type evmServicePingPong struct {
	stream client.Stream
}

func (x *evmServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *evmServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *evmServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *evmServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *evmServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *evmServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Evm service

type EvmHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Evm_StreamStream) error
	PingPong(context.Context, Evm_PingPongStream) error
}

func RegisterEvmHandler(s server.Server, hdlr EvmHandler, opts ...server.HandlerOption) error {
	type evm interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Evm struct {
		evm
	}
	h := &evmHandler{hdlr}
	return s.Handle(s.NewHandler(&Evm{h}, opts...))
}

type evmHandler struct {
	EvmHandler
}

func (h *evmHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.EvmHandler.Call(ctx, in, out)
}

func (h *evmHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.EvmHandler.Stream(ctx, m, &evmStreamStream{stream})
}

type Evm_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type evmStreamStream struct {
	stream server.Stream
}

func (x *evmStreamStream) Close() error {
	return x.stream.Close()
}

func (x *evmStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *evmStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *evmStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *evmStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *evmHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.EvmHandler.PingPong(ctx, &evmPingPongStream{stream})
}

type Evm_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type evmPingPongStream struct {
	stream server.Stream
}

func (x *evmPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *evmPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *evmPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *evmPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *evmPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *evmPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
